name: Publish to PyPI

on:
  release:
    types: [published]
  # Alternatively, trigger on version tags
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # For trusted publishing (recommended):
        # 1. Go to https://pypi.org/manage/account/publishing/
        # 2. Add a new pending publisher with:
        #    - PyPI Project Name: emoji-index
        #    - Owner: nquest-corp
        #    - Repository: emoji-index
        #    - Workflow name: publish-to-pypi.yaml
        #    - Environment name: (leave blank)

        # Alternatively, use API token (less secure):
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
